### ISSUE TITLE
Cite single item

### ISSUE THREAD

**Issue by languitar** [pcooksey/bibtex-js#15]
Is it somehow possible to create a full citation for a single entry from a longer bibtex database with this?

**Comment by pcooksey** [comment]
Yes, this is possible but it hasn't been added to the master branch yet. This is a duplicate issue of #14. Check out this [branch](https://github.com/pcooksey/bibtex-js/tree/limitBibtexDisplay). Below is the usage to display a single entry (or multiple single entries throughout the page):
```
<bibtex src="mybibfile.bib"></bibtex>
<div class="bibtex_display" bibtexkeys="knuth1890math"></div>
<div class="bibtex_display" bibtexkeys="key2"></div>
```

**Comment by languitar** [comment]
Ok thank you. That looks like what I need.

**Comment by davidmainzer** [comment]
Any chance to get this feature merged into master?

**Comment by pcooksey** [comment]
Yes, I have added the feature to master in abeec72eb0501d2f6ae41ed4f778b4a60e75984f
