### ISSUE TITLE
How to add a link based on bib data

### ISSUE THREAD

**Issue by tobiasdiez** [pcooksey/bibtex-js#16]
I would like to add a link to the arxiv based on the data stored in the `eprint` field, i.e. something like
````html
<a href="https://arxiv.org/abs/<<put eprint here>>" target="_blank">
    arXiv:<span class="eprint"></span>
</a>
````
but I couldn't find a way to put the correct url there (i.e. replace `<<put eprint here>>` by the contents of the eprint field). The code (similar to what is described in the wiki)
````html 
<a href="https://arxiv.org/abs/+eprint+" target="_blank" extra="eprint">
````
seems not to work

Thanks!

Ps: On a related note, the code 
https://github.com/pcooksey/bibtex-js/blob/237827702ea39190c5094df2d8866b2c46748f37/src/bibtex_js.js#L432-L436
does not work and should be replaced by
````javascript
var self = this;
tpl.find("a." + key.toLowerCase()).each(function() {
   if (!$(this).attr("href")) {
      $(this).attr("href", self.fixValue(value));
   }
});
````
I'll provide a PR with a few more fixes soon.

**Comment by tobiasdiez** [comment]
I was able to fix this on my own. The problem was that the key was expected to be in upper case. Since the other fields are replaced with lowercase fields, I think this should also work for these special replacements. I'll provide a fix soon.

**Comment by dgraziotin** [comment]
@tobiasdiez were you able to get it to extract other fields at the end? I was trying to get the doi field of a bibtex file, but no luck.

**Comment by pcooksey** [comment]
Closed: Fixes were implemented into master branch
