### ISSUE TITLE
How to treat punctation with non-existing data

### ISSUE THREAD

**Issue by tobiasdiez** [pcooksey/bibtex-js#17]
Let's say I have an custom template that ends with the following code
```html
<span class="if address"><span class="address"></span>, </span>
<span class="if volume"><span class="volume"></span></span>
````
If the entry has a `volume` then everything is fine and I get something like `my address, vol4`. But if no volume is specified, a superfluous comma is added at the end, i.e. `my address, `.
Is there a way to remove this comma?

**Comment by pcooksey** [comment]
In this case, I would move the comma in front of the volume since you only need it when volume is specified. See below:
```html
<span class="if address"><span class="address"></span></span>
<span class="if volume">, <span class="volume"></span></span>
```

**Comment by tobiasdiez** [comment]
Ok, this may work for most cases. Sometimes, a bit more control would be nice. For example, it seems to be possible to generate the following output:
````
address
address, pages
address, pages. volume
address, volume
`̀ ``
(because in your solution one would have to put the comma and the point in the `if volume` span).

[BibLaTeX](http://ctan.mackichan.com/macros/latex/contrib/biblatex/doc/biblatex.pdf) has a quite sophisticated algorithm (described in section 4.7.2-5), which may give some inspiration.

**Comment by pcooksey** [comment]
Okay, I believe the following solution works for this situation. More if/else statements can be added for more complex situations. Also I cannot access your link. 
```html
<span class="if address"><span class="address"></span></span>
<span class="if pages">, <span class="pages"></span></span>
<span class="if volume"> 
    <!-- Here we can implement an if statement for the punctuation --> 
    <span class="if pages">.</span>
    <span class="if !pages">,</span>
    <span class="volume"></span>
</span>
```

**Comment by tobiasdiez** [comment]
Ok, that's a nice solution. It would be a bit more readable if a test like `if notlast` would be supported, i.e
````html
<span class="if address"
    <span class="address"></span>
    <span class="if notlast">,</span>
</span>
<span class="if pages">
    <span class="pages"></span>
    <span class="if notlast">.</span>
</span>
<span class="if volume"> 
    <span class="volume"></span>
</span>
````
But for me, your solution is also fine and you can close this issue if you want. 

Here the correct link to biblatex: http://tug.ctan.org/macros/latex/exptl/biblatex/doc/biblatex.pdf

**Comment by pcooksey** [comment]
I don't think I want to add another key term like `notlast` since the check for each if statement does not look ahead at future if statements. I could see the addition of `or` and `and` to the if logic so that the code looks similar to yours. This method would keep the logic in the designers hands:

```html
<span class="if address">
    <span class="address"></span>
    <span class="if pages or volume">,</span>
</span>
<span class="if pages">
    <span class="pages"></span>
    <span class="if volume">.</span>
</span>
<span class="if volume"> 
    <span class="volume"></span>
</span>
```
I don't know how much use this would get from people using bibtexjs.

**Comment by pcooksey** [comment]
Closing
