### ISSUE TITLE
URL tag

### ISSUE THREAD

**Issue by davidmainzer** [pcooksey/bibtex-js#20]
Hello,

i tried to use URL provided inside of the BibTex:

<span class="if url" style="margin-left: 20px">
  <a class="url">(view online)</a>
</span>

but it does not work. I can't find a working example within the wiki pages. It would be great if you can provide a hint.

Many thanks in advance.

**Comment by pcooksey** [comment]
Were you using the simple:
`<div id="bibtex_display"></div>`
or a custom display?
Also in your bibtex was your url formatted like `\url{http://link.com}`
The \url was not being removed by mistake. I fixed this issue in 8295904d192aca9f17d9b1a8a3083455d383fddd

**Comment by davidmainzer** [comment]
I used the simple
<div class="bibtex_display"></div>
command.
I will test the new version. Many thanks in advance.

**Comment by pcooksey** [comment]
I implemented a test for this issue in 73723b4539c24b190de4d743645858bce1167a4b so closing issue.
