### ISSUE TITLE
jquery loaded in http: breaks usage on https: sites

### ISSUE THREAD

**Issue by fuhrmanator** [pcooksey/bibtex-js#21]
I'm trying out bibtex-js on the new Google Sites (Embed) and it won't load because of `Mixed Content` errors:

> ... was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.

I copied the entire Javascript for bibtex-js to the Embed and changed the URL for that jquery module to have https: and it's working.

**Comment by pcooksey** [comment]
Commit: 15b6bfdcc87679f7dcf4e157a3dcb8f193d50560 changed jquery link from http to https.

Okay, I created a very simple example in Googles Sites (Embed) to test bibtex_js and it now seems to work as expected ([link](https://sites.google.com/csumb.edu/testing-embedded-bibtexjs/home)).
