### ISSUE TITLE
Using class="bibtex_display" instead of id="bibtex_display" will make seach dysfunctional

### ISSUE THREAD

**Issue by j-4** [pcooksey/bibtex-js#23]
Hello,
First of all, nice framework - I find it very useful for my webpage!
I found a little inconsistency between your documentation and the code. The documentation clearly states `Use the class attribute instead of id. Include all bibtex keys you want displayed in bibtexkeys="key1|key2|...|keyN".`

However, doing so will make the `hideEntry()` and the `unhideAll()` functions not doing their job, as they just search for `$("div#bibtex_display")`. They should also include `$(".bibtex_display")` children!

Thanks for your work,
Stefan

**Comment by pcooksey** [comment]
All right this has been merged into master (82553f167e2888ee49cfe6cbd2ff2194ebc1c873). Closing.
