### ISSUE TITLE
XML Parsing Error: syntax error

### ISSUE THREAD

**Issue by alexpacini** [pcooksey/bibtex-js#27]
### Edit 2
I don't get the error when it is on GitHub Pages, but only when opened locally.
Maybe related to this? https://stackoverflow.com/questions/42630246/xml-parsing-error-in-firefox-developer-console

### Edit
I tried without comments but the result is the same, therefore my guess on comments was wrong.
I changed the title.

### Original
If in the .bib file there is a comment before the entry like:

```
%%%%%%%%%%%%%%%%%%%
%% Journals
%%%%%%%%%%%%%%%%%%%

@Article{Pacini_2017_TMTT_LoadandPositionIndependent,
  author    = {Alex Pacini and Alessandra Costanzo and Samer Aldhaher and Paul D. Mitcheson},
  title     = {{Load- and Position-Independent Moving {MHz} {WPT} System Based on {GaN}-Distributed Current Sources}},
  journal   = {{{IEEE} Transactions on Microwave Theory and Techniques}},
  year      = {2017},
  volume    = {65},
  number    = {12},
  pages     = {5367--5376},
  month     = dec,
  doi       = {10.1109/tmtt.2017.2768031},
  url		= {http://dx.doi.org/10.1109/tmtt.2017.2768031},
}
```
it results in:
```
XML Parsing Error: syntax error
Location: file:///C:/Users/alex/Documents/git/alexpacini.github.io/StaticContent/pubList/AlexPacini.bib
Line Number 1, Column 1:
```
Actually, everything that's not inside a bibtex entry should be ignored if I am not wrong.
https://tex.stackexchange.com/questions/93972/comment-out-sections-of-text-in-bib-file
https://tex.stackexchange.com/questions/21709/comments-in-bibtex

**Comment by pcooksey** [comment]
It seems you are trying to view the html file directly rather than through a web server which will cause problems. This is not a problem with bibtex-js. You need to have some server hosting the files. For example, run `python -m SimpleHTTPServer` in the folder with the html file and then view it with `0.0.0.0:8000/youfile.html` using firefox. Hope that helps.
