### ISSUE TITLE
Make an author bold

### ISSUE THREAD

**Issue by alexpacini** [pcooksey/bibtex-js#28]
I would like to print a selected author name as bold text, is it possible?

**Comment by pcooksey** [comment]
This is currently not possible, but it should be possible in the near future. This should be possible after I finish normalizing the authors.

**Comment by pcooksey** [comment]
Look at the [CSS formatting for authors](https://github.com/pcooksey/bibtex-js/wiki/Formatting-Authors#css-formatting). Basically, add the authors formatting and then use CSS to bold a particular author name. <b>Remember</b> to update your bibtex_js file or reference.
```css
[class="First Last"] {
  font-weight: bold;
}
```
