### ISSUE TITLE
<bibtex> fails when used with Vue.js

### ISSUE THREAD

**Issue by jtebert** [pcooksey/bibtex-js#36]
I am trying to use this within a page generate by [Nuxt](https://nuxtjs.org/). It works if I embed bib content with a textarea. However, when I try to use the `<bibtex>` tag, I get the following error:

    Unknown custom element: <bibtex> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 

It seems that Vue is trying to interpret the tag as its own. Any way to avoid this, or a way to import a .bib file without using the bibtex HTML tag?

**Comment by jtebert** [comment]
Found a solution! (Might be useful in case anyone else runs across the same problem. I just had to add the flag `v-pre` to the tag so Vue wouldn't try to interpret the component as its own:

`<bibtex v-pre ...>`

**Comment by faroit** [comment]
@jtebert just found  your comment regarding bibtex parsing in vue. Are you actually using this for your [website](https://github.com/jtebert/juliaebert.com)? Couldn't find this in a repo.

Thinking a step ahead, I think the idea of a bibtex vue component would  really help fostering researchers  to use vue for their personal website.  Would also be nice together with vuepress.
I think it would be great to have an external vue bibtex plugin!

**Comment by jtebert** [comment]
I ended up handrolling my own JSON-based (instead of bibtex-based) components in the interest of time. [Here's the kind-of-hacky-component I made for my site.](https://github.com/jtebert/juliaebert.com/blob/master/components/PublicationList.vue) It lets you add filters by type or key, so I can display individual publications or whole categories, and it lets you select an author name to highlight (which is nice for a CV). I've also started directly compiling my CV into a PDF from HTML, so having this as my canonical publication source is nice.

I think there was some challenge I ran into using your package, but I can't recall what anymore; it's been a few months. It might have been related to the ability to filter or display multiple on a page?

Regardless, I do think it would be cool to come up with a Vue component for this. (I used Nuxt for my website, but I think it's equally applicable to both Nuxt and VuePress.) From what I've seen in my current research group, there's definitely a reluctance to build a website from scratch, but this might ease the pain a little bit.

**Comment by faroit** [comment]
> Regardless, I do think it would be cool to come up with a Vue component for this. (I used Nuxt for my website, but I think it's equally applicable to both Nuxt and VuePress.) From what I've seen in my current research group, there's definitely a reluctance to build a website from scratch, but this might ease the pain a little bit.

@jtebert cool, hacktober is over. But maybe I will start something new over christmas. I will contact you
@pcooksey are you interested as well? your fork is probably the most stable js bibtex parser right now...
