### ISSUE TITLE
<span class="if BIBTEXTYPE==article">Artikel</span>

### ISSUE THREAD

**Issue by Abakaba** [pcooksey/bibtex-js#37]
Can I use the if statement also for BIBTEXTYPE?

**Comment by pcooksey** [comment]
Please checkout the develop branch (2e6098d1ae27d076b6a59c3c51ae563ddbb342a0) and let me know if it handles your case. I added `==` to the if statements. So in your case it should work like so:
```html
<span class="if BIBTEXTYPEKEY==@ARTICLE">Artikel</span>
```
Notice that I've used `BIBTEXTYPEKEY` and not `BIBTEXTYPE` which is set internally to defined values. The wiki was missing `BIBTEXTYPEKEY` [updated wiki link](https://github.com/pcooksey/bibtex-js/wiki/Extras/_edit#additional-bibtex-fields). Also, `@ARTICLE` needs to be capitalized and have an `@` symbol in the beginning.

**Comment by Abakaba** [comment]
Cool! This works nicely! Many thanks.
This allows me now to have a lable on the publication type per bibtex entry.
As soon as my page is ready, I will share it with you.

**Comment by Abakaba** [comment]
I am just wondering if you plan to merge this feature in the master branch?
Furthermore, it seems like the develop branch (2e6098d) an d all latest branches do not display special characters. e.g. {\~n} or {\'o}.

I would really appreciate if you can generate one version which contains the functionality
<span class="if BIBTEXTYPEKEY==@ARTICLE">Artikel</span> and displays special characters.

Many thanks in advance.

**Comment by pcooksey** [comment]
Of course! Just got a little busy. I've merged the `==` into master (2e6098d1ae27d076b6a59c3c51ae563ddbb342a0). 

As for the displaying special characters, 
> 4. Special characters are entered as `{\"a}` or `{\"{a}}` not `\"{a}`.

So you should escape the special character. This was found in [Chapter 2 Helpful Tips](https://mirror.hmc.edu/ctan/biblio/bibtex/contrib/doc/btxFAQ.pdf)
So, it works for me when doing `{\~n}`

That said, I do believe there are some lingering issues with the special character display. So I'll create a new issue #38 for generating a test for all the special characters that are supported by bibtex. However, this may take some time as I am in the middle of other work.

**Comment by pcooksey** [comment]
I'm closing this issue. Please refer to issue #38 if you are still having issues with displaying special characters.
