### ISSUE TITLE
style "(view online)"

### ISSUE THREAD

**Issue by rettinghaus** [pcooksey/bibtex-js#39]
The link text `(view online)` should be inside a separate `<span>` with dedicated `@class`, something like `"bibtex_url"`, to make it stylable.

**Comment by pcooksey** [comment]
This is an issue with the default template? You can of course customize the template to do exact that:

```html
<div class="bibtex_template">
    <div class="if author" style="font-weight: bold;">
      <span class="if year">
	<span class="year"></span>, 
      </span>
      <span class="author"></span>
      <span class="if url" style="margin-left: 20px">
	<a class="url">
	  <span class="bibtex_url"> <!-- Your customized class for the view online text -->
	    (view online)
	  </span>
	</a>
      </span>
    </div>
    <div style="margin-left: 10px; margin-bottom:5px;">
      <span class="title"></span>
    </div>
</div>
```

```css
.bibtex_url { color:blue; font-size: 14px; }
```

The default template is just the default. It can never handle all use cases, which is exactly why bibtex-js is made to be customized. The [wiki](https://github.com/pcooksey/bibtex-js/wiki) explains it best.

**Comment by rettinghaus** [comment]
Yes,  thanks! I meant the default template.

**Comment by pcooksey** [comment]
Great, I'm glad I could help. 

I'm closing this issue since your question is more on customizing the `bibtex_template`, which I demonstrated above, then with the default template.
