### ISSUE TITLE
Custom group headers don't have id attributes

### ISSUE THREAD

**Issue by lynn9388** [pcooksey/bibtex-js#47]
As I want to group a reading list with year, the default header is h1, and its id is set with the year. That works fine with TOC.

```html
<div class="bibtex_structure">
  <div class="group year" extra="DESC number">
      <div class="sort journal" extra="DESC string">
        <div class="templates"></div>
      </div>
  </div>
</div>
```

![Screen Shot 2019-08-01 at 9 23 38 PM](https://user-images.githubusercontent.com/6847317/62296902-ab1cbe00-b4a2-11e9-98d3-6a008a7dca91.png)

But after I set the header to h2 according to [custom-group-headers](https://github.com/pcooksey/bibtex-js/wiki/Customizable-Template#custom-group-headers) the id is empty, and TOC doesn't work.

```
<div class="bibtex_structure">
  <div class="group year" extra="DESC number">
      <div class="sort journal" extra="DESC string">
        <h2 class="title"></h2>
        <div class="templates"></div>
      </div>
  </div>
</div>
```

![Screen Shot 2019-08-01 at 9 26 23 PM](https://user-images.githubusercontent.com/6847317/62297055-06e74700-b4a3-11e9-9c7b-7b5da80c738d.png)

My temporary solution is set the id with javascript like this

```javascript
$(".title").each(function() {
    $(this).attr("id", $(this).text());
});
```

This works fine with TOC, but still leads to other problems. Is there any chance to fix this, or provides a way to access the group name, so I can set the header like this

```html
<div class="bibtex_structure">
  <div class="group year" extra="DESC number">
      <div class="sort journal" extra="DESC string">
        <h2 class="groupname" id="+groupname+"><span class="group name"></span><</h2>
        <div class="templates"></div>
      </div>
  </div>
</div>
```

**Comment by pcooksey** [comment]
Okay, it seems I mistakenly didn't add the value to the id when adding the custom group header. This is a very simple fix (checkout this [branch](https://github.com/pcooksey/bibtex-js/tree/groupCustomHeaderIdFix)). However, my concern is that you said your temporary javascript solution worked but had other problems. What other problems? My provided solution in the new branch shouldn't be really any different from your javascript solution. 

Let me know if my solution works or if you have other issues. I'll merge the branch into master once we have determined the solution works for you.

As for variable access that doesn't work because it is in the `bibtex_structure`. That being said, the only variable to access would be the group value and that can be accessed through the `class=title`. Unless you can think of a reason for implementing the `class=bibtexVar` within the `bibtex_structure`, I don't see that as a solution.

**Comment by lynn9388** [comment]
Your solution works, and you could merge that branch.

The other issue is I use [TOC](http://tscanlin.github.io/tocbot/) and [Anchor links](https://www.bryanbraun.com/anchorjs/) in [my page](https://lynn9388.github.io/wiki/reading-list-of-blockchain.html), and they rely on the headers and their ids already exist before they execute. As I know bibtex-js spends a little time to parse bibtex file, but I don't see the callback function after it finished (If it exists, it might be better.). So I fix my problem with this:

```javascript
$(window).on("load", function () {
    anchors.remove("h2");
    anchors.add("h2");
    tocbot.refresh();
});
```

**Comment by pcooksey** [comment]
Okay, great!

Ah that makes sense. I've been thinking about this and I could add a simple callback attribute for the bibtex_display and have it executed once everything has been generated. 
```html
<div id="bibtex_display" callback="function(bibtex_display)"></div>
```
which then gets converted into:
```javascript
if($("#bibtex_display").attr("callback")) {
  var callback= new Function('bibtex_display', $("#bibtex_display").attr("callback"));
  callback($("#bibtex_display")[0]);
}
```
so the code inside the `callback` attribute gets executed and has access to the `bibtex_display` element. I would then probably add the same type of callback to every `bibtexentry` but that doesn't really relate to what you need.

**Comment by lynn9388** [comment]
That sounds great!

**Comment by pcooksey** [comment]
Okay, you can uses the callback as I previously described.
Commit: 8c78c995accb5ee1c0c8ae07bf93eea0b408401e

Closing this issue. Open a new issue if you have a problem with the callback functionality. I think it is pretty straight forward so hopefully there won't be any problems.

**Comment by lynn9388** [comment]
I have tested that commit, it works. Great job! 👍
