### ISSUE TITLE
Use jsdelivr instead of raw git

### ISSUE THREAD

**Issue by alexpacini** [pcooksey/bibtex-js#51]
Rawgit is getting discontinued. Better use jsdelivr.

https://cdn.jsdelivr.net/gh/pcooksey/bibtex-js/src/bibtex_js.js

**Comment by pcooksey** [comment]
Thanks for letting me know. I've changed the wiki page to display the jsdelivr link.

When I have time I will change the link below (that is inside of bibtex_js) from:
"https://rawgit.com/moment/moment/2.22.2/min/moment.min.js"
to
"https://cdn.jsdelivr.net/gh/moment/moment@2.22.2/min/moment.min.js"

This should be the only other rawgit link (checked with a [quick search](https://github.com/pcooksey/bibtex-js/search?q=rawgit&unscoped_q=rawgit))
