### ISSUE TITLE
Selective display of publications and multiple lists on a single page

### ISSUE THREAD

**Issue by RecklessCoding** [pcooksey/bibtex-js#57]
First, a huge thank you for your work. It saved me so much time. Particularly as I haven't coded in Javascript since 2013! 

There are two things I have trouble figuring out:
1. Is it possible to display by default only publications with a specific keyword or bibtexkey (i.e. without having to select through a list)? A hack I found is to create a Select elements with a selected option element and a preset value. You can set the Select item display:none via CSS. However, I would love to hear a better way.
2. Can you embed multiple publications lists at different parts of a single page? E.g. show one or two papers right after some text, then have more text and another short list of publications right after that. In my unsuccessful attempt of having two <div id="bibtex_display"> elements, upon rendering the page I would get one merged list whether the first <div id="bibtex_display"> was placed.

Thank you in advance for any pointers/help!

PS: I made some minor changes, which I pushed.

**Comment by pcooksey** [comment]
I'm glad its been useful! And welcome back to web development =) 

Have you looked at this part of the wiki: https://github.com/pcooksey/bibtex-js/wiki#selecting-bibtex-entries

The examples below this section show how to select bibtex entries using the bibtexkey or author.

Let me know if this doesn't work for you. It was designed for this exact purpose of having multiple lists on a single page with different bibtex entries.

**Comment by RecklessCoding** [comment]
Hey! Thank you for the response.

It is an "interesting" coffee-fueled journey. ;-) 

I tried to follow those instructions at first, but I was still getting only one bibtex_display. After spending some time trying to debug the issue, I had a "duh moment" and realised how simple the bug was. I was using a `<div id="bibtex_display">` instead of `<div class="bibtex_display">`. Obviously as IDs are meant to be unique, the library was getting confused and outputting everything to the first `bibtex_display`. Note, the live demo uses id instead of class too, which is probably how I introduced that bug; i.e. by copying without thinking. 

What might be useful is to expand the selection bibtex fields to include keywords. I may work on that and push it to my fork later this week (unfortunately, reviewing takes priority).

**Comment by pcooksey** [comment]
Yes, the demo is demonstrating the standard one bibtex_display. The wiki does say to use `class` when trying to select.

I don't know what you mean by include keywords. If you have a bibtex field called keywords then you can also select on that `keywords="something"`. If you want to select on the entire bibtex entry then you can probably use `bibtexraw="keywords"`. 

I looked at your fork. You are adding stuff that is already possible, but that I believe should be implemented in html. 

You added new text for different `BIBTEXTYPEKEY`
But if you want this you would write this using [operators](https://github.com/pcooksey/bibtex-js/wiki/Customizable-Template#operators):
```html
<span class="if BIBTEXTYPEKEY==ARTICLE">Article</span>
<span class="if BIBTEXTYPEKEY==BOOK">Book</span>
```
for all your different types. 

However, your commit says better support for selecting on types which makes me think you just want this then (note values needs to be capitalized):
```html
<div class="bibtex_display" bibtextypekey="INPROCEEDINGS"></div>
<div class="bibtex_display" bibtextypekey="BOOK"></div>
<div class="bibtex_display" bibtextypekey="JOURNAL|ARTICLE"></div>
```

And, the urls have an entire [page](https://github.com/pcooksey/bibtex-js/wiki/URL-DOI-Hyperlinks) on them which will do exactly what you wanted. The example is already DOI. 

The editor should probably be added though.

**Comment by RecklessCoding** [comment]
I did try this
`<div class="bibtex_display" keyword="x"></div>`
but it did not work. 

On my commit(s), what is different is that the options generated by
```html
<select class=" bibtex_search bibtex_generate_bibtextypekey form-control" search="bibtextypekey"></select>
```
will have a more easy-to-read (in my opinion) label. E.g. instead of:
```html
<option label="INPROCEEDINGS">
``` 
, you get:
```html
<option label="Proceedings">
```
Moreover, it adds a CSS class, so you can have a colorful list, matching any other visual identification you may have for the different types of `BIBTEXTYPEKEY`. It has nothing to do with the
```html
<div class="bibtex_display" bibtextypekey="FOO"></div>
```

I also use the library for Talks, not only for Publications. For Talks, I have an `upcoming` bibtex field, which is missing by most entries of that bib. What I did is to generate options to display filter upcoming talks via:
```html
<select class="bibtex_search bibtex_generate_upcoming ">
```
If the field is missing, then the option gets the `value="null"` instead of `value=""` as it would by default. Then, in `bibtex_js_draw` function, I deal with the `null` value accordingly.  What this allows me to do is to have options in the selection box to either display only upcoming talks (if any) or filter them out.

WRT URL and DOI, I do not think that it should be one or the other.  Quite often, you may have a URL to an OpenAccess repository in addition to the DOI link. I prefer to display both, as the journal may not have an open-access version of the paper. This might be more common for us in Europe, where our institutions require (or at least encourage) us to upload any publications into their OA repositories and have their own deals with the publishers for OA. I have also added support for generating arXiv links with the `arxivid` field.

You can see how I use this version on my website: www.recklesscoding.com Just to be clear, I am not debating that you should fork my changes over, as these are hacks based on my own preferences and needs.

I understand that you would rather do things in HTML; I am the opposite. I would rather minimise the HTML part as I find it more tedious to read. In any case, thank you again for both the library and your engagement.

**Comment by pcooksey** [comment]
Ah I see. I hadn't taken a close enough look to realize it was about the select options. From your previous messages I was assume it was still about selecting bibtex entries. My bad.

I was only trying to suggest that you might be reinventing the wheel, but I can understand wanting to keep within javascript. For my case and the library its becomes a challenge because everyone wants something else as shown by your usage. So, the html part makes it easier to provide options rather than hard-coded ways in javascript. I can easily find someone who would want the select label to have some prefix or suffix or something else slightly different.

WRT URL and DOI, you can have both the URL and DOI with the html code I linked. Its just another if statement. But no matter you have your solution already. 

I really like the select with different color coding! Looks good!
