### ISSUE TITLE
Add tags

### ISSUE THREAD

**Issue by alexpacini** [pcooksey/bibtex-js#60]
Using jsdelivr on the master branch can unexpectedly break things.
Is it possible to release versions on npm or to add tag to the repo using some semantic versioning? This way it avoids to break things.

Thanks!

**Comment by mhaeussermann** [comment]
I second that!

**Comment by pcooksey** [comment]
I completely agree! And, sorry for the delay. Here is the official [v1.0.0 release](https://github.com/pcooksey/bibtex-js/releases/tag/v1.0.0).

Most of the details are in the release, and I've provided links for the jsdelivr using the released version.

I'll close this ticket but reopen it if there are any other issues.
