### ISSUE TITLE
Problems with example

### ISSUE THREAD

**Issue by dhowe** [pcooksey/bibtex-js#8]
I see the following error when I try the html below (derived from your example) in Chrome:

`Refused to execute script from 'https://raw.githubusercontent.com/pcooksey/bibtex-js/master/src/bibtex_js.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.`

My HTML:

```
<html>
<head>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script type="text/javascript" src="https://raw.githubusercontent.com/pcooksey/bibtex-js/master/src/bibtex_js.js"></script>
</head>
<body>
<textarea id="bibtex_input" style="display:none;">
@book{book1,
  author = "Donald Knuth",
  title = "Concrete Mathematics"
}
</textarea>
<div id="bibtex_display"></div>
</body>
</html>
```

In Firefox, or when I download bibtex_js.js locally to avoid the above error, I see a blank page:

![screen shot 2017-02-13 at 8 18 14 pm](https://cloud.githubusercontent.com/assets/737638/22883123/99effd6a-f229-11e6-8b80-cd54f425a2c9.png)

**Comment by pcooksey** [comment]
Thanks for letting me know!
The first issue was with Github adding Content-Type: text/plain to the headers of their raw files. I changed the link to a different hosting website. It is advisable for performance to locally host the src file though.
The second issue was a bug with the default template not being added to the website. 

It should be fixed now.

**Comment by dhowe** [comment]
Thanks much -- would also be great if you included a complete (but minimal) html test file on the installation page, to minimize the cutting/pasting (and guessing)...
