### ISSUE TITLE
Hints for displaying sub-sets of a bibtex file based on type

### ISSUE THREAD

**Issue by fuhrmanator** [pcooksey/bibtex-js#9]
It's common for academics to want to show only sub-sets (groups) one at a time, e.g.,

## Book chapters ##

(list of of pubs that are @INCOLLECTION)

## Journal articles ##

(list of of pubs that are @ARTICLE)

etc.

So far, the group by bibtextype is not bad, but not ideal (it's an alphabetical list, and I can't customize the headers for a page in another language).

I know I could do it with separate .bib files, but obviously that is not much fun to maintain them. 

I used to use bibtexbrowser when it was on publications.li, but now I've found bibtex-js and am quite happy. Here's how the bibtexbrowser doc described academic style: http://www.monperrus.net/martin/bibtexbrowser/#HowtousetheAcademicstyle -- perhaps this is a feature request?

**Comment by pcooksey** [comment]
The whole purpose of this project was to maintain a single .bib file and not worry about compiling html every time the .bib file changes. Definitely a needed enhancement since I wouldn't want you maintaining multiple files either.

Okay, I've created a new branch to test out the custom groupings you want [Academic Style](/pcooksey/bibtex-js/tree/academicstyle). It lets you define sections using the new bibtextypekey (`@article` and such). There is an example code below. Let me know if this is what you wanted.

```html
<div class="bibtex_structure">
  <div class="sections bibtextypekey">
      <div class="section @article" title="Refereed Articles"></div>
      <div class="section @book" title="Books"></div>
      <div class="section @inproceedings" title="Conference and Workshop Papers"></div>
      <div class="section @misc|@phdthesis|@mastersthesis|@bachelorsthesis|@techreport" title="Other Publications"></div>
      <div class="templates"></div>
  </div>
</div>
```

**Comment by fuhrmanator** [comment]
Looks great and it's an amazingly fast response. I'm going to try it tomorrow on my desktop PC.

**Comment by pcooksey** [comment]
Closing: 
- Commit: 10cae25b02615490fc5ab3716995824b4b03e422 merged academic style into master branch.
- Commit: fee7ad9e38d0fffd46f946ec462e2ed087fd982c added tests for the new style.
- Documentation added to explain the academic style in [wiki](https://github.com/pcooksey/bibtex-js/wiki/Styles#academic-style).

**Comment by fuhrmanator** [comment]
I finally had some time to try this (thanks for implementing it). It's working, but it seems that within a section (e.g., `@article`) the entries are sorted by author name by default (rather than year, which is what I would expect). Can you give a hint in the wiki on how to sort each section by year (that would be the more common default I think). That is, I couldn't figure out where to put:

    <div class="sort year" extra="DESC string"></div>

inside:

    <div class="bibtex_structure">
      <div class="sections bibtextypekey">
        <div class="section @article" title="Refereed Articles"></div>
        <div class="section @book" title="Books"></div>
        <div class="section @inproceedings" title="Conference and Workshop Papers"></div>
        <div class="section @misc|@phdthesis|@mastersthesis|@bachelorsthesis|@techreport" title="Other Publications"></div>
        <div class="templates"></div>
      </div>
    </div>

**Comment by fuhrmanator** [comment]
I think I figured it out (I looked at the test in https://github.com/pcooksey/bibtex-js/commit/fee7ad9e38d0fffd46f946ec462e2ed087fd982c):

    <div class="bibtex_structure">
      <div class="sections bibtextypekey">
        <div class="section @article" title="Refereed Articles"></div>
        <div class="section @book" title="Books"></div>
        <div class="section @inproceedings" title="Conference and Workshop Papers"></div>
        <div class="section @misc|@phdthesis|@mastersthesis|@bachelorsthesis|@techreport" title="Other Publications"></div>
	<div class="sort year" extra="DESC date">
        <div class="templates"></div>
      </div>
    </div>

Before I saw the `date` option for sorting, I was sorting on `number`, e.g., `<div class="sort year" extra="DESC number"></div>`, and the result was inconsistent; the year as a number was sorted ASC rather than DESC. If you specify DESC it sorts with ASC (seems like the logic is flipped for `number` at least when you use `year`.

**Comment by pcooksey** [comment]
I've updated the documentation in the [wiki](https://github.com/pcooksey/bibtex-js/wiki/Styles#academic-style) for sorting within the sections. My mistake for leaving that out.
Also, thank you for pointing out the bug in sorting by number.

Commit: c35eb551c5aca5073c6637e9acf9caaaf6e148d6 fixed the bug when sorting by number.

**Comment by fuhrmanator** [comment]
FYI my Google Site is still a draft, but the [publications page](https://sites.google.com/etsmtl.net/cfuhrman/publications) is working well. I put the .bib file on a secre t GitHub Gist, so I can just update it there. Thanks again for the Academic Style!
